version: '3'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: cpf-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "8080:80"

  users:
    build: ./users
    image: cinema/users
    container_name: cinema-users
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: users.local

  db:
    image: mongo:3.3
    container_name: cinema-db
    volumes:
      - ./backup:/backup:rw

