version: '3'

services:

  proxy:
    image: jwilder/nginx-proxy
    container_name: cpf-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "8080:80"

  api:
    build: ./api
    image: cpf/api
    container_name: cpf-api
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: cpf-api.local

  db:
    image: mongo:3.6.0-jessie
    container_name: cpf-db
    volumes:
      - ./backup:/backup:rw

