version: '3'
services:

  nginx:
    image: nginx
    container_name: cpf-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf-d:/etc/nginx/conf.d
      - vhost-d:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - "./proxy/certs:/etc/nginx/certs:ro"
      - "./proxy/htpasswd:/etc/nginx/htpasswd:ro"

  nginx-gen:
    image: jwilder/docker-gen
    container_name: cpf-nginx-gen
    volumes:
      - conf-d:/etc/nginx/conf.d
      - vhost-d:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - "./proxy/certs:/etc/nginx/certs:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup cpf-nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: cpf-letsencrypt-nginx-proxy-companion
    links:
      - nginx
    volumes:
      - conf-d:/etc/nginx/conf.d
      - vhost-d:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - "./proxy/certs:/etc/nginx/certs:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  api:
    build: ./api
    image: cpf/api
    container_name: cpf-api
    depends_on:
      - db
    links:
      - db
    volumes:
      - html-public:/root/public
    environment:
      - VIRTUAL_HOST=cpf.mydomain.org
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=cpf.mydomain.org
      - LETSENCRYPT_EMAIL=cpf@mydomain.org

  db:
    image: mongo:3.6.0-jessie
    container_name: cpf-db
    volumes:
      - ./backup:/backup:rw

  frontend:
    build: ./frontend
    image: cpf/frontend
    container_name: cpf-frontend
    volumes:
      - html-public:/home/node/public
    #environment:
      #- VIRTUAL_HOST=cpf.mydomain.org
      #- VIRTUAL_NETWORK=nginx-proxy
      #- VIRTUAL_PORT=3000
      #- LETSENCRYPT_HOST=cpfapi.mydomain.org
      #- LETSENCRYPT_EMAIL=cpfapi@mydomain.org

volumes:
  conf-d:
  vhost-d:
  nginx-html:
  html-public:
